log4js:
  level: "debug"

nightmare:
  show: false
  gotoTimeout: 5000
  waitTimeout: 5000
  loadTimeout: 5000
  executionTimeout: 5000
  pollInterval: 100
  typeInterval: 5
  maxAuthRetries: 2

enavi:
  loginUrl: "https://www.enavi-sv.net/ts-s-staff/Staff/login.aspx?ID=XXXXXXXXX"
  staffNo: "no"
  password: "password"
